apiVersion: v1
kind: Pod
metadata:
  name: basic-kafka
spec:
  containers:
  - name: kafka 
    image: bitnami/kafka:latest
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "localhost:2181"
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
  - name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
     - containerPort: 2181
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
